name: smooth_counter
description: A Flutter package that is a smooth running counter widget.
version: 0.1.0
repository: https://github.com/KyoheiG3/smooth_counter
documentation: https://github.com/KyoheiG3/smooth_counter
issue_tracker: https://github.com/KyoheiG3/smooth_counter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
